services:

  aptp:

    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: aptp-01

    restart: unless-stopped

    network_mode: host

    privileged: true

    volumes:

      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../data:/app/data
      - /etc/hostname:/etc/host_hostname:ro
      - /etc/NetworkManager:/etc/NetworkManager
      - /run/NetworkManager:/run/NetworkManager
      - /var/run/dbus:/var/run/dbus

    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"

    command: /usr/local/bin/start-dev.sh